src/pkglists/ghci-osbuild

`pytest` is nicer to use than the standard `unittest` module. The `cov` plugin for it provides coverage support.

containers/ghci-osbuild: add pytest and pytest-cov

---

.github/workflows/containers.yml

Currently, it can happen that while `PUSH` and `RELEASE` environment
variables in the CI environment get set to `false`, the `MIRROR`
variable is still set to `true`. As a result, images will be built as
part of CI, they won't be pushed and released, but they will be tried to
be mirrored on Quay.io and Dodkerhub.
This is especially an issue for CI runs on pull requests, on which the
`PUSH` and `RELEASE` are set to `false`, but mirroring is still
attempted and fails due to missing credentials to respective services.
In fact `MIRROR` is probably always set to `true`, because the
`${GITHUB_REPOSITORY}` is presumably always set to `osbuild/containers`
for pull requests in the upstream repository.
This change ensures that `MIRROR` is set to `true` only if also `PUSH`
is set to `true`. …

🏗️ CI: Don't mirror images if they are not pushed

---

src/pkglists/ghci-osbuild

Add python3-iniparse to the list of packages installed on ghci-osbuild
image. The package is a dependency of a new org.osbuild.rhsm stage.
Related to osbuild/osbuild#555.

📦 ghci-osbuild: Include python3-iniparse package

---

src/pkglists/ghci-osbuild

This is needed for triggering schutzbot, see:
https://github.com/osbuild/osbuild/pull/580

ghci-osbuild: add python3-boto* libraries

---

src/pkglists/ghci-osbuild

This is needed for the boot iso work, where lorax templates are used, which depend on python3-mako. osbuild will gain a utility function to parse and execute those templates and thus we need to have the library so pylint can check the code.

ghci-osbuild: add python3-mako package

---

docker-bake.hcl

Related to https://github.com/osbuild/osbuild/pull/689

osbuild-ci: add python3-pyyaml needed by new cloud-init stage

---

docker-bake.hcl

We need the lvm2 utilities in the CI for osbuild to unit tests the `osbuild.utils.lvm2` package.

osbuild-ci: include lvm2 needed for tests

---

docker-bake.hcl
src/config/azure-cli.repo
src/config/google-cloud-sdk.repo
src/images/cloud-tools.Dockerfile

With RHEL-9, the osbuild-composer run into issues related to the CLI
tools provided by each cloud provider. In general they can not be
installed on the RHEL-9 host. This commit adds a new Fedora-based image
with all the necessary CLI tools (for AWS, Azure and GCP), which can be
used in osbuild-composer CI tests to interact with the cloud-provider's
API.
Signed-off-by: Tomas Hozza <thozza@redhat.com>

Add new "cloud-tools" container image.

---

docker-bake.hcl

We need the cryptsetup packaget in the CI for osbuild to tests the `org.osbuild.luks2.format` stage.

osbuild-ci: include cryptsetup needed for tests

---

docker-bake.hcl

To test the open Pull Request to support Arch Linux in osbuild, pacman
is required on the host.

Add pacman to the CI container

---

docker-bake.hcl

The google cloud tool apparently uses a bundled python3, which needs `libcrypt.so.1` but does not declare that as dependency. Since we do not install `libxcrypt-compat` by default, it is broken:
/usr/lib64/google-cloud-sdk/platform/bundledpythonunix/bin/python3:
error while loading shared libraries: libcrypt.so.1:
cannot open shared object file: No such file or directory
Install `libxcrypt-compat` for now to fix it.

Add `libxcrypt-compat` to unbreak google cloud tool

---

docker-bake.hcl

The work on container support (see
https://github.com/osbuild/osbuild/pull/952) needs skopeo to download
containers.

Add skopeo to the CI container

---

docker-bake.hcl

It is end-of-life and should not be used anymore.

Don't build fedora 32 images anymore

---

docker-bake.hcl

Install SSH client in the `cloud-tools` container to allow `gcloud
compute ssh` command, which is just a thin wrapper of the SSH client.
Signed-off-by: Tomas Hozza <thozza@redhat.com>

cloud-tools: install openssh-clients

---

docker-bake.hcl

Add the requests library to the rpmrepo-ci image. This will be used by the repository-configuration validation PR.

image/rpmrepo-ci: add python3-requests

---

docker-bake.hcl

Will be used to check source code formatting.

containers/ghci-osbuild: include autopep8

---

docker-bake.hcl

Will be used to check source code formatting.

containers/ghci-osbuild: include isort

---

src/images/osbuild-ci.Dockerfile

Git recently stopped supporting running `git` from within a directory-path that contains `.git/` ancestors with a different UID. This is to prevent malicious users from injecting code into git-hooks of a different user.
We disable this security measure for the CI, since we do not invoke git from untrusted paths.
CC @gicmo @supakeen (This should fix the git-safe-directory issues of the new CI containers)

images/osbuild-ci: disable git-safe-dir

---

src/actions/ghci-osbuild/action.yml
src/actions/netwait/action.yml
src/actions/privdocker/action.yml

Version 12 will be deprecated summer 2022, see [1].
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Update to node 16

---

.github/workflows/ci-images.yml

The `::set-output` command is deprecated [1] and will be removed in 2023. Use the suggested replacement by writing into `$GITHUB_OUTPUT`.
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: replace `::set-output` with `$GITHUB_OUTPUT`

---

docker-bake.hcl

This is related to: https://github.com/osbuild/osbuild/pull/1133 where we will need to install `osbuild` for the new module-is-executable things to work.

osbuild-ci: add pip

---

docker-bake.hcl

This is needed for the `mkfs.fat` command.
This is needed for https://github.com/osbuild/osbuild/pull/1282

Add dosfstools to osbuild-ci container

---

docker-bake.hcl

This is needed for testing of org.osbuild.librepo source: https://github.com/osbuild/osbuild/pull/1304

osbuild: Add python3-librepo

---

docker-bake.hcl

We will soon have tests for btrfs that require btrfs(1) available. Let's add it to the list.

osbuild: Add btrfs-progs

---

docker-bake.hcl
src/config/google-cloud-sdk.repo
src/images/osbuild-ci-cstream.Dockerfile
src/scripts/dnf.sh
src/scripts/install-oci-cli.sh
src/scripts/pip.sh

Add two new variants of the osbuild-ci image based on c8s and c9s.
**The intention is to use these images to run osbuild unit tests in the upstream, to catch any RHEL incompatibilities early as possible.**
CentOS Stream is lacking some packages. Install all of the unavailable python packages using pip and also pytest on cXs images. The reason is for not installing pytest from cXs repositories is to get the latest version of it to not have to deal with lack of features on older releases.
In addition, the cXs base images contain minimal variants of some packages, which we want to install into them. To resolve the conflicts, allow erasing of packages during package installation.
The intention is that these cXs images will be used mostly to run the unit tests. The Fedora image should be used …

Add osbuild-ci images based on c8s and c9s

---

docker-bake.hcl

When I was adding the c8s and c9s variants of the osbuild-ci image, I first added the '-fedora' suffix to the 'osbuild-ci' image which is based on Fedora. However, I later reverted it back, basically to keep the current version of osbuild CI working without any change. Unfortunately, it turns out that I missed to revert one case of this change. Fixing it now.

Use 'osbuild-ci' name for the Fedora image

---

docker-bake.hcl

test_skopeo_with_localstorage started to fail on c8s. Solution is to install missing fuse-overlayfs package.

Images: Add fuse-overlayfs to cXs CI images

---

docker-bake.hcl

Add the libdnf5 python bindings for testing osbuild-depsolve-dnf5 in osbuild CI.

osbuild: add python3-libdnf5

---

.github/workflows/ci-actions.yml
.github/workflows/ci-images.yml
src/actions/ghci-osbuild/action.yml
src/actions/netwait/action.yml
src/actions/privdocker/action.yml

As suggested by github:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Update to node 20

---

docker-bake.hcl

Centos 10 needs to be used to run daily CI tests
together with c8s and c10s. This commit adds c10s image definition to existing CI images.

Images: Add c10s based image to CI images

---

src/scripts/rpmrepo-snapshot.sh

This cache can be used by the enumerate handler.

rpmrepo-snapshot: support building the snapshots-cache

---

docker-bake.hcl

This is a version testing different approach to package list creation

Image: Update cXs images with missing python library

---

docker-bake.hcl

This will fix the problem that the osbuild-ci built using the latest Fedora does not include the default Python3 version that comes with it (3.13).

osbuild-ci: install python3.13 interpreter

---

src/images/rpmrepo-snapshot.Dockerfile

Fedora 41 has dnf5, which doesn't support the reposync plugin yet.

images/rpmrepo-snapshot: pin base image to fedora 40

---

docker-bake.hcl
src/images/rpmrepo-snapshot.Dockerfile

Fedora 41 has dnf5, which doesn't support the reposync plugin yet.
The previous PR changed the container version used by default if not explicitly specified. However, docker-bake.hcl specifies the container explicitly, so we needed to change it there.

docker-bake: f40 rpmrepo-snapshot 

---

docker-bake.hcl

This commit adds the missing `grub2-tools` that is required in https://github.com/osbuild/osbuild/pull/1946

docker-bake: add `grub2-tools` for osbuild PR#1946

---

docker-bake.hcl

It turned out, that installing grub2-tools is not enough to make 'org.osbuild.grub2.inst' tests run in osbuild. Until now, the test would be skipped, because the `osbuild-ci` image was never updated in the osbuild repository.
See https://github.com/osbuild/osbuild/actions/runs/12834514251/job/35791994053#step:3:274
```
...
stages/test/test_grub2_inst.py::test_grub2_partition SKIPPED (cannot...) [ 18%]
stages/test/test_grub2_inst.py::test_grub2_iso9660 SKIPPED (cannot f...) [ 18%]
...
```
And failures after updating the `osbuild-ci` image https://github.com/osbuild/osbuild/actions/runs/12812586711/job/35724614320?pr=1981#step:3:1244
```
...
/usr/lib64/python3.6/subprocess.py:438: CalledProcessError
----------------------------- Captured stdout call ----------------------------- …
```

osbuild-ci: install grub2-pc-modules

---

docker-bake.hcl

Install the license_expression package, needed for https://github.com/osbuild/osbuild/pull/2023

osbuild-ci: install license_expression

---

docker-bake.hcl

This reverts commit 108122e9af0f298dcb344b47552b3c63b4164615.
DNF5 now has reposync plugin.

Revert "docker-bake.hcl: base rpmrepo-snapshot on fedora 40"
